### ISSUE TITLE
upload on Chromium: missing close button

### ISSUE THREAD

**Issue by remyla** [MatLala/generic-ui#14]
when I use Chromium and upload I see this overlapping warning message:

Upload works only with Firefox,
please use Firefox !

but can't remove it - should click anywhere to remove it or use back or change for a simple warning using alert()

**Comment by MatLala** [comment]
A fontAwesome cross icon is present at top right window .
So if FontAwesome isn't loaded, nothing appear at window to close the warning message.

I will add the possibility to click anywhere to remove the warning message and the replacement of FontAwesome icons with characters (as X) if library is not present.

**Comment by remyla** [comment]
sorry, i don't see any button (fontAwesome or whatever) what is see is this:
```html
<div class="overlayBodyDrop" style="text-align: center;">Upload works only with Firefox,<br>please use Firefox !</div>
```

**Comment by remyla** [comment]
sorry i was using an outdated code, I finally updated it works now, closing the issue
